package com.hermes.analyzer.ai.agents

import com.hermes.analyzer.ai.AdvancedAIEngine

/**
 * Agent 3: Documentation AI
 * 전문 역할: 분석 결과 요약, 리포트 생성, 마크다운 문서화
 */
class DocumentationAgent(private val engine: AdvancedAIEngine) {
    data class Document(
        val title: String,
        val sections: List<Section>,
        val metadata: Map<String, String>
    )

    data class Section(
        val heading: String,
        val content: String,
        val severity: String? = null
    )

    fun generateReport(
        title: String,
        codeAnalysis: CodeAnalyzerAgent.CodeAnalysis?,
        securityReport: SecurityInspectorAgent.SecurityReport?,
        binaryInfo: Map<String, String>?,
        userGoal: String
    ): String {
        val sb = StringBuilder()
        sb.append("# $title\n\n")
        sb.append("**Generated**: ${java.text.SimpleDateFormat("yyyy-MM-dd HH:mm").format(java.util.Date())}\n")
        sb.append("**User Goal**: $userGoal\n\n")
        sb.append("---\n\n")

        // Executive Summary
        sb.append("## Executive Summary\n\n")
        val overallScore = securityReport?.score ?: 100
        val scoreEmoji = when {
            overallScore >= 90 -> "✅"
            overallScore >= 70 -> "⚠️"
            else -> "❌"
        }
        sb.append("${scoreEmoji} **Security Score**: ${overallScore}/100\n\n")
        
        if (codeAnalysis != null) {
            sb.append("- **Language**: ${codeAnalysis.language}\n")
            sb.append("- **Complexity**: ${codeAnalysis.complexity}/20\n")
            sb.append("- **Functions**: ${codeAnalysis.functions.size}\n")
            sb.append("- **Dependencies**: ${codeAnalysis.dependencies.size}\n")
        }
        if (securityReport != null) {
            sb.append("- **Critical**: ${securityReport.criticalCount}\n")
            sb.append("- **Warnings**: ${securityReport.warningCount}\n")
            sb.append("- **Info**: ${securityReport.infoCount}\n")
        }
        sb.append("\n")

        // Code Analysis
        codeAnalysis?.let { analysis ->
            sb.append("## Code Analysis\n\n")
            sb.append("${analysis.summary}\n\n")
            if (analysis.functions.isNotEmpty()) {
                sb.append("### Functions\n\n")
                analysis.functions.forEach { f ->
                    sb.append("- `${f.name}(${f.params.joinToString(", ")})` → ${f.returnType}\n")
                }
                sb.append("\n")
            }
            if (analysis.dependencies.isNotEmpty()) {
                sb.append("### Dependencies\n\n")
                analysis.dependencies.forEach { sb.append("- `$it`\n") }
                sb.append("\n")
            }
        }

        // Security Findings
        securityReport?.let { report ->
            sb.append("## Security Analysis\n\n")
            if (report.findings.isEmpty()) {
                sb.append("✅ No security issues detected.\n\n")
            } else {
                report.findings.forEach { f ->
                    val emoji = when (f.severity) {
                        "critical" -> "🔴"
                        "warning" -> "🟡"
                        else -> "🔵"
                    }
                    sb.append("$emoji **${f.severity.uppercase()}** [${f.category}] ${f.description}\n")
                    sb.append("- Evidence: `${f.evidence}`\n")
                    sb.append("- Fix: ${f.fix}\n")
                    f.cweId?.let { sb.append("- CWE: $it\n") }
                    sb.append("\n")
                }
            }
        }

        // Binary Info
        binaryInfo?.let { info ->
            sb.append("## Binary Information\n\n")
            info.forEach { (k, v) -> sb.append("- **$k**: $v\n") }
            sb.append("\n")
        }

        // Recommendations
        securityReport?.let { report ->
            if (report.recommendations.isNotEmpty()) {
                sb.append("## Recommendations\n\n")
                report.recommendations.forEachIndexed { i, rec ->
                    sb.append("${i + 1}. $rec\n")
                }
                sb.append("\n")
            }
        }

        sb.append("---\n*Report generated by Hermes Analyzer Documentation Agent*")
        return sb.toString()
    }

    fun generateVulnerabilityReport(findings: List<SecurityInspectorAgent.SecurityFinding>): String {
        val sb = StringBuilder()
        sb.append("# Vulnerability Report\n\n")
        val critical = findings.filter { it.severity == "critical" }
        val warnings = findings.filter { it.severity == "warning" }
        val infos = findings.filter { it.severity == "info" }

        sb.append("| Severity | Count |\n")
        sb.append("|----------|-------|\n")
        sb.append("| 🔴 Critical | ${critical.size} |\n")
        sb.append("| 🟡 Warning | ${warnings.size} |\n")
        sb.append("| 🔵 Info | ${infos.size} |\n\n")

        if (critical.isNotEmpty()) {
            sb.append("## Critical Issues\n\n")
            critical.forEach { f ->
                sb.append("### ${f.description}\n")
                sb.append("- Category: ${f.category}\n")
                sb.append("- Evidence: ${f.evidence}\n")
                sb.append("- Fix: ${f.fix}\n")
                f.cweId?.let { sb.append("- Reference: [CWE-$it](https://cwe.mitre.org/data/definitions/$it.html)\n") }
                sb.append("\n")
            }
        }
        return sb.toString()
    }
}
